DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE event (
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  user_id INTEGER NOT NULL,
  start TEXT NOT NULL, 
  end TEXT NOT NULL,
  title TEXT NOT NULL,
  instrument TEXT,
FOREIGN KEY(user_id) REFERENCES user(id)
)